---
branches:
  - master
projects:
  EasyVanish:
    path: ""
    icon: "icon.png"
    lint:
      phpstan: false
    libs:
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^1.1.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
...